"""add organization multi-tenant support

Revision ID: 4e4714ec3a4a
Revises: 1052e2148c41
Create Date: 2026-02-15 13:34:57.463258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e4714ec3a4a'
down_revision: Union[str, Sequence[str], None] = '1052e2148c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.alter_column('assessment_history', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('suppliers', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.add_column('suppliers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'suppliers', 'organizations', ['organization_id'], ['id'])
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'created_at')
    op.drop_column('suppliers', 'organization_id')
    op.alter_column('assessment_history', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
